### ISSUE TITLE
Redirect to wrong URL after creating new Agile Board

### ISSUE THREAD

**Issue by Waizujin** [ubirimi/ubirimi#49] opened 2015-05-24 02:15 UTC
Prerequisites
1. Have a project already created.

Steps to Reproduce
1. Login to your Yongo instance.
2. Click the Agile dropdown.
3. Click Create Board.
4. Enter a Board Name and select a parent Project.
5. Click Create Board.

Expected Result: User is taken to the boards page.
Actual Result: User is redirected to /agile/boards/ which gives a blank white page.

Video: http://screencast.com/t/sZHk5SAx0I

**Comment by w2pc** [comment] 2015-05-24 03:40
This was caused by an error. since error reporting is turned of on production the page just shows white.

**Comment by w2pc** [comment] 2015-05-24 03:42
Fixed in https://github.com/ubirimi/ubirimi/commit/a48fdbb6961e390bffcee8e0cbb6ffdd8f74cf43

**Closed by w2pc** 2015-05-24 03:42 UTC
Labels: bug
